/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.LocadoraVeiculo.Telas;


import br.com.LocadoraVeiculo.TabelaVeiculos.Tela_Categorias;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author edunativa
 */
public class Tela_Area_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Tabela_Veiculos
     */
    public Tela_Area_Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //Metodo que serve para centralizar a JInternalFrame dentro de uma DesktopPane
    private void centralizaJInternalFrame(JInternalFrame frame) {
        Dimension desktopSize = AreaTrabCliente.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        AreaTrabCliente = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        CatalogoDeVeiculos = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        AreaTrabCliente.setToolTipText("");
        AreaTrabCliente.setMaximumSize(new java.awt.Dimension(1024, 768));
        AreaTrabCliente.setMinimumSize(new java.awt.Dimension(800, 600));
        AreaTrabCliente.setName(""); // NOI18N

        fileMenu.setMnemonic('f');
        fileMenu.setText("Veiculos  ");
        fileMenu.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        CatalogoDeVeiculos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        CatalogoDeVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/IconeSetapraDireita.png"))); // NOI18N
        CatalogoDeVeiculos.setMnemonic('o');
        CatalogoDeVeiculos.setText("Catálogo de Veículos");
        CatalogoDeVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatalogoDeVeiculosActionPerformed(evt);
            }
        });
        fileMenu.add(CatalogoDeVeiculos);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Pagamento  ");
        editMenu.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        cutMenuItem.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/InconePagVista.png"))); // NOI18N
        cutMenuItem.setText("À Vista");
        editMenu.add(cutMenuItem);

        copyMenuItem.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        copyMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/IconePagDeb.png"))); // NOI18N
        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("No Debito");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pasteMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/IconePagCred.png"))); // NOI18N
        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("No Crédito");
        editMenu.add(pasteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Contatos");
        helpMenu.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N

        contentMenuItem.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/IconeAtendente.png"))); // NOI18N
        contentMenuItem.setMnemonic('F');
        contentMenuItem.setText("Fale Conosco");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/icone_termo.png"))); // NOI18N
        aboutMenuItem.setMnemonic('N');
        aboutMenuItem.setText("Nossos Termos");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaTrabCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AreaTrabCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(810, 653));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CatalogoDeVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatalogoDeVeiculosActionPerformed
        Tela_Categorias cat = new Tela_Categorias();
        AreaTrabCliente.add(cat);
        cat.setVisible(true);
        centralizaJInternalFrame(cat);
       
        
    }//GEN-LAST:event_CatalogoDeVeiculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Area_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Area_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Area_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Area_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Area_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane AreaTrabCliente;
    private javax.swing.JMenuItem CatalogoDeVeiculos;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
