/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.LocadoraVeiculo.TabelaVeiculos;

import br.com.LocadoraVeiculo.ConexaoBD.ConexaoBD;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author edunativa
 */
public class ConfirmarPag extends javax.swing.JFrame {
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form ConfirmarPag
     */
    public ConfirmarPag() {
        initComponents();
        conexao = ConexaoBD.conector();
        jPanelFormsPag.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFormasPag = new javax.swing.ButtonGroup();
        btnConfrmarPag = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanelPag = new javax.swing.JPanel();
        jPanelPesquisa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPesqCpf = new javax.swing.JButton();
        jFormattedCPF = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanelFormsPag = new javax.swing.JPanel();
        jRadioButtonAVista = new javax.swing.JRadioButton();
        jRadioButtonDebito = new javax.swing.JRadioButton();
        jRadioButtonCredito = new javax.swing.JRadioButton();
        jPanelDadosPag = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTotalAVista = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalDebito = new javax.swing.JLabel();
        txtTotalCredito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formas de Pagamento");
        setResizable(false);

        btnConfrmarPag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/iconeSIM.png"))); // NOI18N
        btnConfrmarPag.setText("Confirmar");
        btnConfrmarPag.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/IconeNao.png"))); // NOI18N
        btnConfrmarPag.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/iconeSIM.png"))); // NOI18N
        btnConfrmarPag.setEnabled(false);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar");

        jPanelPag.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelPesquisa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPesquisa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Entre com o Número do seu CPF, depois clique em Pesquisar.");
        jPanelPesquisa.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 8, -1, -1));

        btnPesqCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/IconePesquisa.png"))); // NOI18N
        btnPesqCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqCpfActionPerformed(evt);
            }
        });
        jPanelPesquisa.add(btnPesqCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 57, 60));

        try {
            jFormattedCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedCPF.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jFormattedCPF.setMargin(new java.awt.Insets(0, 10, 0, 0));
        jPanelPesquisa.add(jFormattedCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 42, 200, 35));

        jLabel2.setText("Formas de Pagamento:");

        jPanelFormsPag.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroupFormasPag.add(jRadioButtonAVista);
        jRadioButtonAVista.setText("À Vista");

        buttonGroupFormasPag.add(jRadioButtonDebito);
        jRadioButtonDebito.setText("Débito");

        buttonGroupFormasPag.add(jRadioButtonCredito);
        jRadioButtonCredito.setText("No Crédito");

        jPanelDadosPag.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Valor à Pagar: R$ ");

        txtTotalAVista.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTotalAVista.setText("0");
        txtTotalAVista.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setText("Valor no Débito: R$ ");

        jLabel5.setText("Valor no Crédito: R$ ");

        txtTotalDebito.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTotalDebito.setText("0");
        txtTotalDebito.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtTotalCredito.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTotalCredito.setText("0");
        txtTotalCredito.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanelDadosPagLayout = new javax.swing.GroupLayout(jPanelDadosPag);
        jPanelDadosPag.setLayout(jPanelDadosPagLayout);
        jPanelDadosPagLayout.setHorizontalGroup(
            jPanelDadosPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosPagLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelDadosPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDadosPagLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDadosPagLayout.createSequentialGroup()
                        .addGroup(jPanelDadosPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(jPanelDadosPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalAVista, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanelDadosPagLayout.setVerticalGroup(
            jPanelDadosPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosPagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTotalAVista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalDebito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalCredito))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFormsPagLayout = new javax.swing.GroupLayout(jPanelFormsPag);
        jPanelFormsPag.setLayout(jPanelFormsPagLayout);
        jPanelFormsPagLayout.setHorizontalGroup(
            jPanelFormsPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormsPagLayout.createSequentialGroup()
                .addGroup(jPanelFormsPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormsPagLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormsPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAVista)
                            .addComponent(jRadioButtonDebito))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormsPagLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButtonCredito)
                        .addGap(18, 18, 18)))
                .addComponent(jPanelDadosPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFormsPagLayout.setVerticalGroup(
            jPanelFormsPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormsPagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormsPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelDadosPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFormsPagLayout.createSequentialGroup()
                        .addComponent(jRadioButtonAVista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDebito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonCredito)
                        .addGap(12, 12, 12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPagLayout = new javax.swing.GroupLayout(jPanelPag);
        jPanelPag.setLayout(jPanelPagLayout);
        jPanelPagLayout.setHorizontalGroup(
            jPanelPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFormsPag, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelPagLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPagLayout.setVerticalGroup(
            jPanelPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFormsPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnConfrmarPag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton3)
                    .addComponent(btnConfrmarPag)
                    .addComponent(btnCancelar))
                .addGap(20, 20, 20))
        );

        setSize(new java.awt.Dimension(538, 334));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    
    public void Consultar(){
        String sql = "select * from Clientes where cpf=?";
         try {
            
            pst = conexao.prepareStatement(sql);
            pst.setString(1, jFormattedCPF.getText());
           
            //A linha abaixo executa a consulta acima no Banco de Dados;
            rs = pst.executeQuery();
            
            if(rs.next()){
              
               jPanelFormsPag.setVisible(true);
               
                                
            }else{
                
                JOptionPane.showMessageDialog(null, "CPF não Encontrado!");
            
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Um Erro Aconteceu!\nNão Valor Inválido:  "+e);
        
        }
        
    }
    
    //Ação do Botão de pesquisa do CPF no Banco de dados do Cliente
    private void btnPesqCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqCpfActionPerformed
      
        Consultar();
        
    }//GEN-LAST:event_btnPesqCpfActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarPag.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmarPag().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfrmarPag;
    private javax.swing.JButton btnPesqCpf;
    private javax.swing.ButtonGroup buttonGroupFormasPag;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedCPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelDadosPag;
    private javax.swing.JPanel jPanelFormsPag;
    private javax.swing.JPanel jPanelPag;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JRadioButton jRadioButtonAVista;
    private javax.swing.JRadioButton jRadioButtonCredito;
    private javax.swing.JRadioButton jRadioButtonDebito;
    private javax.swing.JLabel txtTotalAVista;
    private javax.swing.JLabel txtTotalCredito;
    private javax.swing.JLabel txtTotalDebito;
    // End of variables declaration//GEN-END:variables
}
